# Generated code do not commit.
file(TO_CMAKE_PATH "D:\\Flutter\\flutter_windows_3.41.4-stable\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "D:\\Flutter\\APLIKASI_ABSENSI_PEGAWAI_BERSIH\\project_final" PROJECT_DIR)

set(FLUTTER_VERSION "1.0.0+1" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 1 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=D:\\Flutter\\flutter_windows_3.41.4-stable\\flutter"
  "PROJECT_DIR=D:\\Flutter\\APLIKASI_ABSENSI_PEGAWAI_BERSIH\\project_final"
  "FLUTTER_ROOT=D:\\Flutter\\flutter_windows_3.41.4-stable\\flutter"
  "FLUTTER_EPHEMERAL_DIR=D:\\Flutter\\APLIKASI_ABSENSI_PEGAWAI_BERSIH\\project_final\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=D:\\Flutter\\APLIKASI_ABSENSI_PEGAWAI_BERSIH\\project_final"
  "FLUTTER_TARGET=D:\\Flutter\\APLIKASI_ABSENSI_PEGAWAI_BERSIH\\project_final\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDEuNA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZmYzN2JlZjYwMw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ZTRiOGRjYTNmMQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMS4x"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=D:\\Flutter\\APLIKASI_ABSENSI_PEGAWAI_BERSIH\\project_final\\.dart_tool\\package_config.json"
)
